---
name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: list
        run: tree ${{ github.workspace }}
      - name: build
        run: bash ${{ github.workspace }}/build.sh
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}/ASSETS.md
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            *.tgz