---
name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: list
        run: tree ${{ github.workspace }}
      - name: build
        run: bash ${{ github.workspace }}/build.sh
      - name: dsenv-zsh.tgz
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dsenv-zsh.tgz
          asset_name: dsenv-zsh.tgz
          tag: ${{ github.ref }}
          overwrite: true
